# Generated by Django 5.0.6 on 2024-05-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wing',
        ),
        migrations.AddField(
            model_name='profile',
            name='Category',
            field=models.CharField(blank=True, choices=[('STUDENT', 'STUDENT'), ('RECRUITER', 'RECRUITER')], max_length=10),
        ),
    ]
