# Generated by Django 5.0.6 on 2024-05-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_wing_profile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camps',
        ),
    ]
